### ISSUE TITLE
Facette crashing on collections update

### ISSUE THREAD

**Issue by i0oi** [facette/facette#209]
When executing: 
``` 
curl -s -H 'Content-type: application/json' -XPUT 'https://<host>/api/v1/library/collections/aa22d3fc-d93f-47cc-78ca-318f5a3d8939/' -d@file.json
``` 
With this data: 
``` 
# cat file.json
{
	"name": "Graph Name",
	"entries": [
		{ "id": "76dc00b8-5fc1-4c26-4db3-c1f2ebcf538a" },
		{ "id": "47d507b3-a3ab-4927-5f8a-d145c96043cf" },
		{ "id": "9e6b40f9-a479-46c5-5873-1575414a38b7" }
	]
}
``` 
I got:
``` 
2015/05/19 19:03:19 http: panic serving 127.0.0.1:46859: assignment to entry in nil map
goroutine 16160 [running]:
net/http.func·011()
        /usr/lib/go/src/net/http/server.go:1130 +0xbb
github.com/facette/facette/pkg/library.(*Library).PrepareCollection(0xc208106780, 0xc208171ce0, 0x0, 0x0, 0x0)
        /tmp/buildd/facette-0.3.0/build/facette-linux-amd64/src/github.com/facette/facette/pkg/library/collection.go:54 +0x2b5
github.com/facette/facette/pkg/server.(*Server).serveBrowseCollection(0xc20802fd90, 0x7fd468f62b50, 0xc208466980, 0xc2084b0820, 0x0, 0x0)
        /tmp/buildd/facette-0.3.0/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/serve_browse.go:96 +0x2bb
github.com/facette/facette/pkg/server.(*Server).serveBrowse(0xc20802fd90, 0x7fd468f62b50, 0xc208466980, 0xc2084b0820)
        /tmp/buildd/facette-0.3.0/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/serve_browse.go:31 +0x28c
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.serveBrowse)·fm(0x7fd468f62b50, 0xc208466980, 0xc2084b0820)
        /tmp/buildd/facette-0.3.0/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:60 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2083d6200, 0x7fd468f62b50, 0xc208466980, 0xc2084b0820)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2083d22a0, 0x7fd468f62b50, 0xc208466980, 0xc2084b0820)
        /usr/lib/go/src/net/http/server.go:1541 +0x17d
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc2083d61a0, 0x7fd468f62af0, 0xc208514f00, 0xc2084b0820)
        /tmp/buildd/facette-0.3.0/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x153
net/http.(*ServeMux).ServeHTTP(0xc20803ac60, 0x7fd468f62af0, 0xc208514f00, 0xc2084b0820)
        /usr/lib/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20837f2c0, 0x7fd468f62af0, 0xc208514f00, 0xc2084b0820)
        /usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208514dc0)
        /usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1751 +0x35e
```

**Comment by vbatoufflet** [comment]
Thanks for reporting this.

It has been fixed in 48220a123018e4072f427be1a5a131f95d27c680.
